### ISSUE TITLE
Cannot run the software

### ISSUE THREAD

**Issue by jtklein** [dongzhang0725/PhyloSuite#18] opened 2020-07-15 13:58 UTC
I can not start the software on MacOS Catalina, an error occurs with "Python" can not be verified.
Was trying from the provided installer on the releases page.

**Comment by dongzhang0725** [comment] 2020-07-16 03:24
Did you try to install "PhyloSuite_v1.2.1_Mac.zip" package on the releases page and follow this installation tutorial (https://dongzhang0725.github.io/dongzhang0725.github.io/installation/)? If you used this file, it may not rely "Python" anymore. 
If you cannot resolve it, please send me the detailed error code, and I will try to debug it.

**Comment by jtklein** [comment] 2020-07-16 10:08
I was trying to install 'PhyloSuite_v1.2.1_Mac_with_plugins.zip' from the release pages according to those instructions, yes.

**Comment by jtklein** [comment] 2020-07-16 10:13
My OS is in German, but here's the error message.
<img width="448" alt="Bildschirmfoto 2020-07-16 um 12 12 36" src="https://user-images.githubusercontent.com/17345891/87659367-c0473700-c75d-11ea-978d-38a3a0c6e597.png">

**Comment by dongzhang0725** [comment] 2020-07-17 03:24
It is hard to read German for me, but it seems that your Mac cannot confirm that Python/PhyloSuite is not malware. You may manually add them to trusted apps list. 
Also, judging by the error message, your computer failed to run PYTHON, and not PhyloSuite. If you installed the PhyloSuite version with packaged Python, it does not require the Python installed on your computer to run any more. 
So this is most probably caused by safety settings of your computer.

**Comment by HannesOberreiter** [comment] 2021-04-27 17:41
Adding a link with a solution to this old question, so this Issue can be closed: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by dongzhang0725** [comment] 2021-04-29 08:45
Good suggestion, closed this thread.

**Closed by dongzhang0725** 2021-04-29 08:45 UTC
